name: Check Code Conventions

on: [push, pull_request]  # Trigger bij een push of pull request

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Haal de repository op

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Kies de Java versie

      - name: Install dependencies
        run: mvn install -DskipTests  # Installeer dependencies zonder tests

      - name: Run Checkstyle
        run: mvn checkstyle:check  # Voer de Checkstyle plugin uit
