name: Java Code Conventions Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Run checkstyle with Google's conventions
      run: |
        mkdir -p target/checkstyle-result
        wget -O google_checks.xml https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml
        java -jar $(wget -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.3.3/checkstyle-10.3.3-all.jar) -c google_checks.xml -f xml -o target/checkstyle-result/checkstyle-result.xml src/ || true
        
    - name: Upload checkstyle results
      uses: actions/upload-artifact@v3
      with:
        name: checkstyle-results
        path: target/checkstyle-result/
        
    - name: Check for style violations
      run: |
        if grep -q "<error " target/checkstyle-result/checkstyle-result.xml; then
          echo "Checkstyle found violations. See uploaded artifacts for details."
          exit 1
        else
          echo "No checkstyle violations found."
        fi