name: Java Checkstyle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Download Checkstyle and Google Style Guide
        run: |
          wget -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.3.3/checkstyle-10.3.3-all.jar
          wget -O google_checks.xml https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml

      - name: Run Checkstyle with Google Style Guide
        run: |
          java -jar checkstyle.jar -c google_checks.xml $(find Jabberpoint-main/src -name "*.java")
        continue-on-error: true
        
      - name: Publish Checkstyle results
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'checkstyle-result.xml'
