name: Check Code Conventions

on: [push, pull_request]  # Trigger on push or pull request

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checkout the repository

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Use Java version 17

      - name: Install dependencies
        working-directory: /jabberpoint-main  # Set working directory
        run: mvn install -DskipTests  # Install dependencies without tests

      - name: Run Checkstyle
        working-directory: /jabberpoint-main  # Set working directory
        run: mvn checkstyle:check  # Run Checkstyle plugin