name: CI Pipeline

on:
  push:
    branches:
      - dev
      - test
      - acceptance
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install --file Jabberpoint-main/pom.xml

      - name: Run Checkstyle for code quality
        run: mvn checkstyle:check --file Jabberpoint-main/pom.xml

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn test --file Jabberpoint-main/pom.xml -Djava.awt.headless=true

  acceptance:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/acceptance'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Deploy to Acceptance
        run: echo "Deploying to Acceptance environment"

  production:
    runs-on: ubuntu-latest
    needs: acceptance
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Deploy to Production
        run: echo "Deploying to Production environment"