name: Run Unit Tests

on: [push, pull_request]  # Trigger on push or pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checkout the repository

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Choose the Java version

      - name: Install dependencies
        run: mvn install -DskipTests  # Install dependencies without tests

      - name: Run Unit Tests
        run: mvn test  # Run unit tests
