name: Run Unit Tests

on: [push, pull_request]  # Trigger bij een push of pull request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Haal de repository op

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Kies de Java versie

      - name: Install dependencies
        run: mvn install -DskipTests  # Installeer dependencies zonder tests

      - name: Run Unit Tests
        run: mvn test  # Voer de unittests uit
